# Makefile for the multi-process Blockchain project
# Initial skeleton: to be completed progressively.

CC      := gcc
CFLAGS  := -Wall -Wextra -std=gnu11 -pthread
LDFLAGS := -pthread
LDLIBS  := -lssl -lcrypto

BUILD_DIR := build
BIN_DIR   := bin

.PHONY: build run clean test debug sanitize demo

build:
	@echo "TODO: compile bootstrap, node, miner, client into $(BIN_DIR)/"

run:
	@echo "TODO: launch ./$(BIN_DIR)/bootstrap with default parameters"

clean:
	@echo "TODO: remove $(BUILD_DIR)/ and $(BIN_DIR)/"

test:
	@echo "TODO: run tests/run_all_tests.sh"

debug:
	@echo "TODO: build with debug symbols (-g -O0)"

sanitize:
	@echo "TODO: build with -fsanitize=address,undefined"

demo:
	@echo "TODO: run scripts/demo.sh"
